### ISSUE TITLE
🚀 [feature] EVENT 관련 api 개발

### ISSUE THREAD

**Issue by HyoBN** [2024-dino/dino-BE#16]
## 🤖 기능 개요

event 관련 api (생성, 조회 등)를 개발합니다.
## ✅ Todo
- [ ] event 생성 api 개발
- [ ] 페이지별 event 조회 dto adapter 코드 작성
- [ ] 페이지별 event 조회 api 개발
