### ISSUE TITLE
🚀 [feature] API 호출/응답 형식 통일 및 스웨거 도입

### ISSUE THREAD

**Issue by HyoBN** [2024-dino/dino-BE#3]
## 🤖 기능 개요

API 호출/응답 형식을 통일하고 스웨거 및 get, post test API 를 구현합니다.
## ✅ Todo
- [ ] API 호출/응답 형식 통일
- [ ] global 에러 핸들링 로직 구현
- [ ] 스웨거 세팅
- [ ] get, post test api 구현
